### ISSUE TITLE
Whos steve jobs?

### ISSUE THREAD

**Issue by theendercore** [mlo40/ligma.io#1]
You don't need the menu and close icons my friend u can just draw them with css. That way u can also save on not loading more images.

**Comment by mlo40** [comment]
![not-funny-didnt-laugh-the-holy-one-58285384](https://user-images.githubusercontent.com/22353705/203241030-fc7b863c-7009-4856-80a0-76f193ee9a71.png)

**Comment by mlo40** [comment]
![6821d70e7806580a89ba52565eb9c3da19fa570b9684a6411d9b9a92bca60381_1](https://user-images.githubusercontent.com/22353705/203241050-1f2e2fb6-2324-49ac-a56a-2c8bc55c921a.jpg)
